services:
  - type: web
    name: baba-milk-delivery
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run_production:app
    envVars:
      - key: FLASK_ENV
        value: production
